#!/usr/bin/env python

# copy/paste the following into a standalone 'fetch_changelog_settings' file,
# and amend with the appropriate information:

repo = 'MRtrix3/mrtrix3'
user = 'YOUR_GITHUB_USERNAME'
# set this to your personal access token, which can generate from GitHub at:
# https://github.com/settings/tokens
password = 'YOUR_GITHUB_TOKEN'







import os, subprocess, requests, sys

try:
  with open('fetch_changelog_settings') as fd:
    exec (fd.read())
except:
  sys.stderr.write ('no fetch_changelog_settings file found - using built-in defaults')



def get_list_of_merges (base, branch):
  list = []
  cmd = ['git', 'log', '--oneline', base + '...' + branch ]
  #sys.stderr.write (' '.join (cmd) + '\n')
  for line in subprocess.check_output (cmd).decode(encoding='utf-8').splitlines():
    if 'Merge pull request #' in line:
      list.append (int (line.split()[4][1:]))

  return list



def get_pull_request (number):
  url = 'https://api.github.com/repos/' + repo + '/pulls/' + str(number)
  resp = requests.get (url, auth= (user, password))

  if resp.status_code != 200:
    sys.stderr.write ('error fetching request ' + str(number) +' with response: ' + str(resp.status_code) + '\n')
    sys.stderr.write ('URL was "' + url + '"\n')
    print (resp.json())
    sys.exit (1)

  return resp




base_tag = subprocess.check_output (['git', 'describe', '--abbrev=0']).decode(encoding='utf-8').strip()
sys.stderr.write ('using base: ' + base_tag + '\n')

merges = get_list_of_merges (base_tag, 'HEAD')
sys.stderr.write ('found pull requests ' + str(merges) + '\n')


for number in merges:
  sys.stderr.write (str(number) + ' ')
  sys.stderr.flush()
  resp = get_pull_request(number).json()
  description= resp['title']
  user = resp['user']['login']
  body = '\n    '.join (resp['body'].splitlines())
  sys.stdout.write ('- [![|24x24](https://github.com/'+user+'.png?size=24)](https://github.com/'+user+') ['+description+'](https://github.com/MRtrix3/mrtrix3/pull/'+str(number)+') ' + body + '\n')

sys.stderr.write ('\ndone\n')

