#!/usr/bin/env python

import os, subprocess, requests, sys

fetch = True

for arg in sys.argv[1:]:
  if arg.startswith ('--tag='):
    base_tag = arg[6:]
  elif arg == '--no-fetch':
    fetch = False
  elif arg == '--help':
    print ('''
Usage:

    cd target_repo
    <path-to-fetchchangelog-folder>/fetch_changelog [options] > changelog.txt

If necessary, the base tag (the latest point to include in the changelog) can
be specified using the --tag=<tag> option. By default, the most recent tag on
the current branch is used as the base tag.

For testing, you may wish to use the --no-fetch option, which will not use
the GitHub API to fetch the details of each merged pull request.

If you need to get around the rate limiting imposed by the GitHub API, you
can generate a personal access token from your GitHub account settings (under
'Developer Settings'), and add that token in a file called
'fetch_changelog_settings' stored in the root of the target repo (the one you
want the changelog for), in the format:

    user = 'github_handle'
    password = 'github_pat_XXYYYAAA'

''')
    sys.exit (0)
  else:
    sys.stderr.write ('unknown command-line option "'+arg+'" - aborting\n')
    sys.exit (1)



try:
  with open('fetch_changelog_settings') as fd:
    exec (fd.read())
except (FileNotFoundError, IOError):
  sys.stderr.write ('no fetch_changelog_settings file found - using built-in defaults\n')




def get_list_of_merges (base, branch):
  list = []
  cmd = ['git', 'log', '--oneline', base + '...' + branch ]
  #sys.stderr.write (' '.join (cmd) + '\n')
  for line in subprocess.check_output (cmd).decode(encoding='utf-8').splitlines():
    if 'Merge pull request #' in line:
      list.append (int (line.split()[4][1:]))

  return list



def get_pull_request (number):
  url = 'https://api.github.com/repos/' + repo + '/pulls/' + str(number)
  try:
    resp = requests.get (url, auth=(user, password))
  except NameError:
    resp = requests.get (url)

  if resp.status_code != 200:
    sys.stderr.write ('error fetching request ' + str(number) +' with response: ' + str(resp.status_code) + '\n')
    sys.stderr.write ('URL was "' + url + '"\n')
    print (resp.json())
    sys.exit (1)

  return resp

branch = subprocess.check_output (['git', 'rev-parse', '--abbrev-ref', 'HEAD']).decode(encoding='utf-8').strip()
remote = subprocess.check_output (['git', 'rev-parse', '--symbolic-full-name', '--abbrev-ref', branch+'@{u}' ]).decode(encoding='utf-8').strip().split('/')[0]
repo = subprocess.check_output (['git', 'remote', 'get-url', remote]).decode(encoding='utf-8').strip()
if repo.startswith ('git@'):
  [url, repo] = repo[4:].split(':',1)
elif repo.startswith ('https://'):
  [url, repo] = repo[8:].split('/',1)
else:
  sys.stderr.write ('unexpected format for repo URL: "' + repo + '"')
  sys.exit (1)

if url != "github.com":
  sys.stderr.write ('upstream URL for current branch is not on github.com - unable to fetch issue listing\n')
  sys.exit(1)

if repo.endswith ('.git'):
  repo = repo[:-4]

try:
  base_tag
except NameError:
  base_tag = subprocess.check_output (['git', 'describe', '--abbrev=0']).decode(encoding='utf-8').strip()
sys.stderr.write ('fetching changelog since tag "' + base_tag + '" for branch "' + branch + '" on remote: "' + remote + '" (' + repo + ')\n')

merges = get_list_of_merges (base_tag, 'HEAD')
sys.stderr.write ('found pull requests ' + str(merges) + '\n\n')


if not fetch:
  sys.exit (0)

for number in merges:
  sys.stderr.write (str(number) + ' ')
  sys.stderr.flush()
  resp = get_pull_request(number).json()
  description= resp['title']
  user = resp['user']['login']
  if resp['body']:
    body = '\n    '.join (resp['body'].splitlines())
  else:
    body = ''
  sys.stdout.write ('- [<img src="https://github.com/'+user+'.png?size=24" alt="avatar for '+user+'" width=24 height=24 />](https://github.com/'+user+') ['+description+'](https://github.com/MRtrix3/mrtrix3/pull/'+str(number)+') ' + body + '\n\n')

sys.stderr.write ('\ndone\n')

